name: Publish to NPM
on:
  push:
    tags:
      - v4.*
jobs:
  build:
    runs-on: ubuntu-latest
    environment: v4
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
      - run: npm pack
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
